sudo: required
services:
- docker

env:
  matrix:
  - JOB_ARCH=amd64
  - JOB_ARCH=arm64
  - JOB_ARCH=armel
  - JOB_ARCH=armhf
  - JOB_ARCH=i386
  - JOB_ARCH=mips
  - JOB_ARCH=mips64el
  - JOB_ARCH=mipsel
  - JOB_ARCH=ppc64el
  - JOB_ARCH=s390x

before_script:
- docker run --rm --privileged vicamo/binfmt-qemu:latest
- cat /proc/sys/fs/binfmt_misc/qemu-*

script:
- docker build -t laarid/devel:${TRAVIS_BRANCH}-${JOB_ARCH} ${JOB_ARCH}
- docker images

notifications:
  slack:
    rooms:
    - secure: "R/HfSISAO4ygQP207pSrzjzWdpDYQs/dnfIdjWxQDNs9Ph3DsT6Ydtj2O6G62+z9pQFBjP7YSN4G5l8dbaDoZby5hrrJEfeyQ579wT5ENeNiDX0NSrPDEZxNZHIArkO7s445QI2hRMulIV1PEQJtI9i6xH/jZvYakKtwtobBg9DvJ0uj+8/Xt3usKfhqhRNlosmqGIv/yA4U9niag5GTqZNA/lfP1jw/xiKl32WIne3RrpRr+UBm//zJ14oR/CxemHkiOdWuoPKS9O7198KHcAtHRumv9mO+5KBPfpRHov8WPZB2mEvpx9ZeQSrJjUNPO26V3CKp4PT/aUnl3CQBY/NtYluK9ZvwlXrkJD33BtmZr/RoSOwL9sB5sCL1YrTOlhxBOgyMe+dEcVvLgBFDwbu2xIy9IYyYURB4upajLhHR5WnOrMSlmY8mdaD427WlUS4eRrTDbrsRuwDGmCzqCwzZy3xT80VGF5V4mFCy2MlPn2gdZC8aqqmvjFl4M6dr6dWOAfZ8j1L9S/BwLy3lJLz2ZIqVBKmgSmtffo+sM1mYNF26P5Wj+TKibvtUsImosxXa43ksTlE/cdMedEdwci19hTgT85gswMEQ0/x3u5X4t59lE4zb5c+qfn167xegE5RY4VQPSE2CQ02vZjqI13pNyntqFcaAdeQcitdeDmg="
