dist: trusty
sudo: required
services:
- docker

env:
  matrix:
  - JOB_SUITE=stretch JOB_ARCH=amd64
  - JOB_SUITE=stretch JOB_ARCH=arm64
  - JOB_SUITE=stretch JOB_ARCH=armel
  - JOB_SUITE=stretch JOB_ARCH=armhf
  - JOB_SUITE=stretch JOB_ARCH=i386
  - JOB_SUITE=stretch JOB_ARCH=mips
  - JOB_SUITE=stretch JOB_ARCH=mips64el
  - JOB_SUITE=stretch JOB_ARCH=mipsel
  - JOB_SUITE=stretch JOB_ARCH=ppc64el
  - JOB_SUITE=stretch JOB_ARCH=s390x
  global:
  - TESTING_SUITE=$(curl --output - http://ftp.debian.org/debian/dists/testing/Release | grep '^Codename:' | awk '{print $2}')
  - DOCKER_EXEC="sudo docker exec test_container"
  - secure: "kOvEwoUWln7f4tH6LA7CsTsBiCL1ngpfg2s1QK20l+yu95HUbHfTkM9TLzxHSI0foQYSnzTXCw4cCd0k6bIRktaBFa5KOHHktimtT0/sVTtaQxAHxeTTKieRsp5ABaaLifssmssw6gLsusIWxkGFzQrGiDnwl6mrtRqzhgENyxMZVEQuO4QaqORcvTj0OQe7IPQF4Sj1dYrVF4376jRX442vSOxrUK25ZpWt/CbZGLnKS9yK7WHx2plkwqmsib54u6fupJ+k1WbLQ9Rg2IlImjLYHuziKfUA7jcKQ+D4nhTqaxZ2D5verk1vVGIiLt6GHypyJeL+ecIToADiVNHyGaycKACflU0xh+QWDRvTVQh2HoKi6EeVDvwjmsLMnc24jNCaLXg64/ilwBk+b1kqYiY/MuQrEK6vgQqvTq9qSqlZpZY6S5fyd1K36iQskyUp0Ip3P2FqE0tIklJUOitIVu6x9xebfsn4m3K1yfWDSBDRSXrNjrH98v5sA0eFXyrJ0gSmerTk+N5VBhlPbKxGZvPcNgwWjUcqdQf3aeuBlJEIzbDY1Ub0JzSBc9tHmScj3PirlcBHFeqADcobCBUfwuxEVKnKpO0rpDK8b2m2421DzxNhmUNuidQMSj8IYfTUcy9vggvr9iORRG/xMXxkElfPUbXrQQb+tkreK2J2JKI="

branches:
  only: master

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ devel universe'
    packages:
    - binfmt-support
    - qemu-user-static

script:
- docker build -t laarid/devel:${JOB_SUITE}-${JOB_ARCH} ${JOB_SUITE}/${JOB_ARCH}
- if [ "${JOB_SUITE}" = "${TESTING_SUITE}" ]; then
    docker tag laarid/devel:${JOB_SUITE}-${JOB_ARCH} laarid/devel:${JOB_ARCH};
  fi
- git clone -o laarid https://github.com/laarid/package_android-bionic.git test
- |
  sudo docker run --detach --tty \
    --name test_container \
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} \
    --workdir ${TRAVIS_BUILD_DIR}/test \
    --add-host dl.bintray.com:$(nslookup dl.bintray.com | grep -m1 -A1 Name: | grep Address: | awk '{print $2}') \
    laarid/devel:${JOB_SUITE}-${JOB_ARCH} \
    /bin/bash
- ${DOCKER_EXEC} mk-build-deps
    --host-arch ${JOB_ARCH}
    --install --remove
    --root-cmd sudo
    --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
- ${DOCKER_EXEC} dpkg-buildpackage --host-arch ${JOB_ARCH} -i -us -uc -b

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
    docker push laarid/devel:${JOB_SUITE}-${JOB_ARCH};
    if [ "${JOB_SUITE}" = "${TESTING_SUITE}" ]; then
      docker push laarid/devel:${JOB_ARCH};
    fi
  fi

notifications:
  slack:
    rooms:
    - secure: "R/HfSISAO4ygQP207pSrzjzWdpDYQs/dnfIdjWxQDNs9Ph3DsT6Ydtj2O6G62+z9pQFBjP7YSN4G5l8dbaDoZby5hrrJEfeyQ579wT5ENeNiDX0NSrPDEZxNZHIArkO7s445QI2hRMulIV1PEQJtI9i6xH/jZvYakKtwtobBg9DvJ0uj+8/Xt3usKfhqhRNlosmqGIv/yA4U9niag5GTqZNA/lfP1jw/xiKl32WIne3RrpRr+UBm//zJ14oR/CxemHkiOdWuoPKS9O7198KHcAtHRumv9mO+5KBPfpRHov8WPZB2mEvpx9ZeQSrJjUNPO26V3CKp4PT/aUnl3CQBY/NtYluK9ZvwlXrkJD33BtmZr/RoSOwL9sB5sCL1YrTOlhxBOgyMe+dEcVvLgBFDwbu2xIy9IYyYURB4upajLhHR5WnOrMSlmY8mdaD427WlUS4eRrTDbrsRuwDGmCzqCwzZy3xT80VGF5V4mFCy2MlPn2gdZC8aqqmvjFl4M6dr6dWOAfZ8j1L9S/BwLy3lJLz2ZIqVBKmgSmtffo+sM1mYNF26P5Wj+TKibvtUsImosxXa43ksTlE/cdMedEdwci19hTgT85gswMEQ0/x3u5X4t59lE4zb5c+qfn167xegE5RY4VQPSE2CQ02vZjqI13pNyntqFcaAdeQcitdeDmg="
