dist: trusty
sudo: required
services:
- docker

env:
  matrix:
  - ARCH=amd64
  - ARCH=arm64
  - ARCH=armel
  - ARCH=armhf
  - ARCH=i386
  - ARCH=mips
  - ARCH=mips64el
  - ARCH=mipsel
  - ARCH=ppc64el
  - ARCH=ppc64el-next SKIP_TAG=1
  - ARCH=s390x
  global:
    secure: "abqIwyPa3Zed8sJymFYeJkS9Ft3z8DXBs7h0f9c+/8PDxicJd6vo9nczAgWPpjzsMUxXZLG2yom0CmABAt9k6Gb8omuGnR8bDCBENzCnoJjrlIoL2XIR1x51lMrihjlgJ3nuOXWBHScIBCkyT+JCvA206gVoLgx1ueXfLfIrhZSHTB2k6cwvhoXlsC/Gxny2t4waJObC7Pa8Mk0zzCvl5R7VJZzpO17cWVcbX2Wa9rx2Kw3s+wVSm8tC5hFHeE86ZQlrBIbf+JTWf/v9gX3yWOvhEYMM0zTKH6XETDFkcvB9oZPlqW5YvGabaZ7snrwTkvKG9K3eNYJLo+1hHQ8sHyxSQFTImSoeugI4DtRZh92vRL4r7PlvvZHA1m+U/CuJhtv7J9xanI2pRrnYDy7QttXzZBZcrKAt1E3J1IUsHCTvPPcxG560JxsHGtBgW00uhfZO98QntxGKy3c83f057NM4bI2Cv3YaGW7bFsn3Sd8t2N87HZxvZLQ+ym+ON04KdyOoJEjcDDBsyFvd62zpTvZfiD4Co3X3hUD4R2JaCoiTtY27TlEbeLnmrf0C8mZe2a0lx+InlcSUp5/s+GQ48S9qCI7SyOnZB2UkYGK+3ObXeqtbP9D9poJf+LAm2nZQB5rlarXAlOp4P14TbZvQZ+lZbNCCpL3PPgYzdp9fHB4="

matrix:
  fast_finish: true
  allow_failures:
  - env: ARCH=ppc64el-next SKIP_TAG=1

branches:
  only: master

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ devel universe'
    packages:
    - binfmt-support
    - qemu-user-static

script:
- dpkg -s qemu-user-static
- docker build -t laarid/devel:$ARCH $ARCH
- O=$(docker run --rm laarid/devel:$ARCH /bin/bash -c 'ls /usr/bin/qemu-*');
  if [ -n "$O" ]; then
    docker run --rm laarid/devel:$ARCH $O --version;
  fi
- |
  git clone -o laarid https://github.com/laarid/package_laarid-meta.git \
    ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}/laarid-meta;
  docker run --rm \
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} \
    --workdir ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}/laarid-meta \
    laarid/devel:$ARCH \
    debuild -i -us -uc -b

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a -z "${SKIP_TAG}" ]; then
  docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
  docker push laarid/devel:$ARCH;
  fi

notifications:
  slack:
    rooms:
    - secure: "AqxV+PQXnDuLA4jeduqPoFWMTm78CyI3+uGf0aB3YQeZw9vjcM5W7TzozH3MjRnw5JkWxyZGULZJkqklZXRnmJf8ify+6dsd2NeEKB8SEiMwrjaRLwc4/roVCArEJyhhU2o0ZvK/iQitoaC6PBhPcTiockv2eNj7Eqw1krdwnFEwDQ5Qn5ehr6EkjuUd8VdqaUMs/kIGNv7I67Ahg1/a2CHU8W8MmO00B6uZ0UAIDdJhSn5YFNr9wseSKlFXP2aQ9nmyC17q24HMk5rVkkts45Kzp102CPrh9ycZqBsKJjsxUqxfYq2DAq/Tk24AzWKNZQMM1jpwPqom/Tl580TtvfDC1E50LBUtEZweE9dIOtMKQ97TFa/hWrm5l+B4dX9rN8Yy9ifGsxhNmF0PWR8Hj3+kJh4pjfCdGQsvb2OLM30yWSU/SAkAlwZUjeTWvsQ9WVlI8130ltW47AgSfCVwx3inCMZie/fpnpjLBTKIrzpsf6dRvkVRtUIKq3YrpDsmMF7dp/2tj+rDKnq18bHDyPFy9QS0Gls6pIUlKxJZJMXUK/lB3MjC6ByB2kYv+P6Iugt8/F3U2YA8VqrB0QcZpZqxlPGj7awvJqxO6G4i3AEEfpN/KSAPXnx7VKUwLVMmKogKo6P7aQxgIGofo/r/qfRSD2+Qa4HRPolHXmRUvKA="
